spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/CristianLMartinez/practice-project-training-config-props.git"
          timeout: 5
          default-label: main
          clone-on-start: true
          force-pull: true
          search-paths: "config"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
    port: 8888
