spring:
  application:
    name: clients

  config:
    import: optional:configserver:http://localhost:8888/

server:

  port: 8765
eureka:

  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
